version: '3'
services:
  mysql:
    build: ./mysql
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  apache:
      build: ./apache
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - ./docs:/var/www/html
        - ./apache/vhost:/etc/apache2/sites-enabled:ro
        - ./apache/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      depends_on:
        - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - '8080:80'
    volumes:
      - /ssesions
    depends_on:
      - mysql
      - apache